import styles from "../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";
import Router from "next/router";
import Navbar from "../components/Navbar";
import SignUpForm from "../components/SignUpForm";

const Register = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>DoLog Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="panel">
        <section className="panel-block hero is-black is-fullheight">
          <Image
            src="/dolog_background.jpg"
            className="is-fullwidth"
            alt="background"
            layout="fill"
          ></Image>
          <div className="hero-head">
            <Navbar></Navbar>
          </div>
          <div className="container"></div>
          <div className="container is-black is-dark pt-6 mb-0">
            <article className="message is-warning">
              <div className="message-header">
                <p className="has-text-black">Figyelem!</p>
              </div>
              <div className="message-body has-background-dark has-text-light">
                Amennyiben még nem regisztráltál, hozz létre egy új fiókot email
                címmelel és jelszóval, vagy használd
                <strong> Google fiókodat</strong>
              </div>
            </article>
          </div>

          <div className="hero-body">
            <div className="container">
              <div className="columns is-justify-content-center">
                <div className="column is-6-tablet is-5-desktop is-4-widescreen is-3-fullh">
                  <div className="panel-heading has-background-black mb-3">
                    <h1 className="title has-text-warning">Fiók létrehozása</h1>
                  </div>
                  <SignUpForm></SignUpForm>
                </div>
              </div>
            </div>
          </div>
          <div className="container"></div>
          <div className="container"></div>
        </section>
      </main>
    </div>
  );
};

export default Register;
